name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      # Yeh step automatic fresh Android aur baki saara structure create karega
      - name: Re-create Flutter Project Structure
        run: |
          cd ..
          flutter create --org com.example skycast
          cp -r SkyCast-Weather-App/lib skycast/
          cp SkyCast-Weather-App/pubspec.yaml skycast/
          mv skycast SkyCast-Weather-App-New
          rm -rf SkyCast-Weather-App
          mv SkyCast-Weather-App-New SkyCast-Weather-App
          cd SkyCast-Weather-App
          flutter pub get

      - name: Build APK
        run: flutter build apk --release --dart-define=WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
