name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      # Fresh project structure aur Internet permission inject karne ka step
      - name: Re-create Flutter Project Structure
        run: |
          cd ..
          flutter create --org com.example skycast
          cp -r ${{ github.workspace }}/lib skycast/
          cp ${{ github.workspace }}/pubspec.yaml skycast/
          
          # Android Manifest mein Internet Permission explicitly add ki ja rahi hai
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"/>' skycast/android/app/src/main/AndroidManifest.xml
          
          rm -rf ${{ github.workspace }}
          mv skycast ${{ github.workspace }}
          cd ${{ github.workspace }}
          flutter pub get

      # Sahi tareeqe se API key inject karke Build karne ka step
      - name: Build APK
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          cd ${{ github.workspace }}
          flutter build apk --release --dart-define=WEATHER_API_KEY="$WEATHER_KEY" --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
